-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  university text,
  major text,
  bio text,
  website text,
  strength text,
  weakness text,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for tasks / todo list
create table tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text default '',
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table tasks enable row level security;

create policy "Individuals can create tasks."
  on tasks for insert
  with check ( auth.uid() = user_id );

create policy "Individuals can view their own tasks."
  on tasks for select
  using ( auth.uid() = user_id );

create policy "Individuals can update their own tasks."
  on tasks for update
  using ( auth.uid() = user_id );

create policy "Individuals can delete their own tasks."
  on tasks for delete
  using ( auth.uid() = user_id );

-- Create a table for Study Sessions
create table study_sessions (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users not null,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  meet_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table study_sessions enable row level security;

create policy "Everyone can view study sessions."
  on study_sessions for select
  using ( true );

create policy "Users can create study sessions."
  on study_sessions for insert
  with check ( auth.uid() = created_by );
